name: rjnumber_fileconverter
description: "RJ Number - File converter xlsx to vcf"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  file_picker: ^12.2.0
  excel: ^4.0.6
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.2
  lottie: ^3.1.2
  window_manager: ^0.4.3
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/logo.svg
    - assets/animation/loading.json
    - assets/animation/convert.json
    - assets/animation/call.json
    - assets/animation/licenas.json
    - assets/animation/nolicence.json
    - assets/animation/yeslicence.json
    - assets/licence/licence.json
    - assets/logo/applogo.png
    - assets/icon/discord.svg
    - assets/icon/github.svg
    - assets/icon/gitlab.svg
    - assets/icon/web.svg
    - assets/icon/youtube.svg
    - assets/icon/blogger.svg

flutter_launcher_icons:
  image_path: "assets/logo/applogo.png"
  android: false
  ios: false
  macos:
    generate: false
  windows:
    generate: true
    icon_size: 256